// TTS Audio URLs for demonstration
// In a real implementation, these would be generated by a TTS service
export const TTS_AUDIO_URLS = {
  welcome: "/api/tts?text=Olá! Vamos começar sua avaliação.",
  speakNow: "/api/tts?text=Agora fale o que deseja compartilhar.",
  npsQuestion: "/api/tts?text=Gostaria de avaliar sua experiência com uma nota de 0 a 10?",
  npsInstructions: "/api/tts?text=Como você avalia sua experiência? De 0 a 10.",
  additionalComment: "/api/tts?text=Gostaria de deixar um comentário adicional por voz?",
  thanks: "/api/tts?text=Obrigado por sua participação!",
};

// For now, we'll use empty strings to simulate TTS
// In production, you would integrate with a real TTS service
export const getTTSAudioUrl = (text: string): string => {
  // This is a placeholder - in real implementation, you would:
  // 1. Call a TTS service (Google Cloud TTS, ElevenLabs, etc.)
  // 2. Return the generated audio URL
  // 3. Cache the results for performance
  
  console.log("TTS requested for:", text);
  return "";
};